# ============================================================================
# Kubernetes ConfigMap - Application Configuration
# ============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: urlshortener-config
  labels:
    app: urlshortener
data:
  db_host: "urlshortener-mysql"
  db_port: "3306"
  db_name: "url_shortener"
  allowed_origins: "https://yourdomain.com,https://www.yourdomain.com"

---
# ============================================================================
# Kubernetes ConfigMap - MySQL Init Script
# ============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  labels:
    app: urlshortener
data:
  init.sql: |
    -- This file is mounted to /docker-entrypoint-initdb.d/init.sql
    -- Add your schema.sql content here or use an init job
